### PR TITLE
feat: add-yaml-support

### PR DESCRIPTION
**Pull request by JuroOravec**
Hi, based on #24, I adeed yaml support.

### Description
Yaml support.

### Details
If the file or url of the labels file ends with .yaml or .yml, the file is parsed as yaml.

I also added an example labels.yml file in case you would want to include a .yml version somewhere in the repo too, as an example.

Lint and tests passed.

I haven't added new tests, though. Wasn't clear where the tests for parsing the file should be added. Guidance on this is welcome.

I haven't changed the documentation. Clarification on that would help too.

Could you have a look at the PR and provide guidance on next steps if the feature would be relevant for this package?

### Relevant Issues
#24

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi @JuroOravec sorry for not getting to this sooner. It unfortunately now has conflicts. If those could be fixed, and some documentation added about yaml support then I will be very happy to merge this in :-)

**Comment by JuroOravec** [comment]
Hi @JakeChampion, no worries, thanks for getting to me! I've updated the branch and updated README. I also suggest to rename the 'Label JSON' section in README to 'Label Config File' as the config file doesn't have to be only JSON anymore (commit included).

Let me know if there's anything else.

Cheers!

**Comment by JakeChampion** [comment]
Thanks, this was released in 1.6.0

**Comment by JuroOravec** [comment]
Thanks @JakeChampion!

**Pull request merged**
