### PR TITLE
Allow HTTP URLs for --labels option

### LINKED ISSUE #7: Allow HTTP urls for the --labels option
The `--labels` options currently only works for local files, but it would be awesome if it could support HTTP URLs too.

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #7

### CODE REVIEW

**Comment by JakeChampion** [comment]
Hi @Turbo87, would you be able to update the documentation with this new feature?

**Comment by Turbo87** [comment]
Yeah, might take bit though since I'm on vacation with spotty internet connection :wink:

**Comment by Turbo87** [comment]
@JakeChampion updated

**Comment by rowanmanning** [comment]
I've released `v1.3.0` which includes your changes 👍

**Pull request merged**
